# Generated by Django 6.0.3 on 2026-05-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('administrator', 'Administrator'), ('teacher', 'Faculty'), ('student', 'Student')], max_length=20),
        ),
    ]
