# Generated by Django 6.0 on 2026-02-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_desc', models.CharField(max_length=100)),
                ('ltps', models.CharField(choices=[('L', 'L'), ('T', 'T'), ('P', 'P'), ('S', 'S')], max_length=1)),
                ('section', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('total_conducted', models.IntegerField(default=0)),
                ('total_attended', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
        ),
    ]
