# Generated by Django 6.0 on 2026-02-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_desc', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=3)),
                ('internal_marks', models.FloatField(default=0)),
                ('external_marks', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('grade', models.CharField(max_length=5)),
                ('grade_points', models.FloatField(default=0)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
        ),
    ]
