# Generated by Django 6.0.4 on 2026-04-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='course_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.course'),
        ),
    ]
