# Generated by Django 6.0.3 on 2026-05-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_alter_grade_course_desc_alter_grade_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
