# Generated by Django 6.0.3 on 2026-05-01 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_hostel_name_student_hostel_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=100, unique=True)),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('mixed', 'Mixed Hostel')], max_length=20)),
                ('warden_name', models.CharField(max_length=100)),
                ('warden_phone', models.CharField(max_length=15)),
                ('warden_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('total_rooms', models.IntegerField()),
                ('capacity_per_room', models.IntegerField(default=2)),
                ('check_in_time', models.TimeField(default='14:00:00')),
                ('check_out_time', models.TimeField(default='10:00:00')),
                ('amenities', models.TextField(help_text='Comma-separated list of amenities')),
                ('rules', models.TextField(blank=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['hostel_name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel_name',
        ),
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.hostel'),
        ),
    ]
